### ISSUE TITLE
Bug no cadastro de nova opção de característica

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#1]
Quando edito uma **Característica** e cadastro **_Nova Opção de Característica_** uma mensagem aparece na tela acusando que duas caractrísticas não podem ter o mesmo nome.
Isso não deve ocorrer porque não estou tentando salvar uma nova característica e sim editando uma já existente no banco.

### _**Index > Características > Editar Característica > Adicionar Nova Opção de Característica > Salvar**_

**Comment by willbigas** [comment]
O comportamento acontecia devido a uma validação de "Nome duplicado" no cadastro da característica, criei um método que faz update na característica e não passa por essa validação e adicionei na tela.
Após isso não consegui mais simular o comportamento da Issue
Closed.
