### ISSUE TITLE
Duas configurações de empresa no mesmo produto 

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#130]
Na página de edit/Produto, na aba configurações, consigo adicionar a mesma empresa n vezes no produto. 

Quando tento excluir uma dessas configurções, não exclui e nem dá retorno ao usuário.

![image](https://user-images.githubusercontent.com/49379484/71583845-e9b8b200-2aee-11ea-94c6-fa748511b300.png)

__--Atualização--__

Percebi que o sistema cria um novo produto para cada configuração de produto por empresa.
![image](https://user-images.githubusercontent.com/49379484/71583835-dd345980-2aee-11ea-92fb-c348cd30a6ce.png)

**Isto é um comportamento esperado? Gostaria de uma explicação.**

Também nessa tela, quando edito as configurações de uma empresa (de um novo produto, com uma única empresa pra configuração), estas não ficam salvas. Tentei várias vezes e não obtive sucesso.
![image](https://user-images.githubusercontent.com/49379484/71584824-3900e180-2af3-11ea-9ab7-979f5eeb4375.png)

__--Meu Deus, agora eu tentei salvar outra empresa nesse produto e não deu certo... Socorro--__

Fazer validação de estoque máximo e mínimo. 
![image](https://user-images.githubusercontent.com/49379484/71586027-710a2380-2af7-11ea-83d2-f9e75c984514.png)

**Comment by willbigas** [comment]
- Criado validação para não permitir o cadastro de empresas iguais no mesmo produto
- Adicionado validação para não permitir estoque mínimo maior que o estoque máximo da empresa

**Comment by LuMistro** [comment]
O sistema fez validação de quantidade máxima e mínima e se a empresa pode ser inserida duas vezes no mesmo produto, porém a validação de localização falhou.

Mesa:
![image](https://user-images.githubusercontent.com/49379484/71599759-f3600b00-2b2a-11ea-8434-21d26cc848a2.png)

Cadeira
![image](https://user-images.githubusercontent.com/49379484/71599775-0246bd80-2b2b-11ea-83d6-be8e855950e7.png)


Como deu pra ver, produtos diferentes na mesma empresa e com a mesma localização.

Como já dizia a impenetrabilidade, na metafísica, dois corpos não podem ocupar um mesmo lugar ao mesmo tempo no espaço...

**Comment by willbigas** [comment]
A issue atual não pedia validação de localização, isso poderia ser aberto em outra issue, mas ok já que está aki irei validar nessa tarefa.

**Comment by LuMistro** [comment]
A necessidade de validação de localização foi concluída em uma reunião hoje pela tarde, e que no final da dia, você disse que já tinha feito a tal validação. Por esse motivo os testes.  
Mas pela sua revolta, abrirei em outra issue e fecharei esta. kkkk
