### ISSUE TITLE
Limpar campos do cadastro de produtos

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#43]
Na tela de listagem de produto, quando vou cadastrar um segundo produto o modal que aparece ainda está com os campos preenchidos.

Precisa criar um método, se esse já não existir no sistema, para limpar os campos do modal após o fechamento do mesmo.

**Comment by willbigas** [comment]
Identificado que a atualização do dialog não estava sendo executada, as chamadas estavam corretas, pós ajuste não consegui mais simular.
