### ISSUE TITLE
Duas características não podem ser cadastradas num mesmo produto

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#53]
Na tela de edit de produto, quando tento cadastrar 2 características iguais com a mesma opção, ele não cadastra, mas trava o sistema e imprime um erro no console.
Isso procisa ser tratado e mostrar uma mensagem ao usuário "**Não é possível cadastrar duas características idênticas no produto**"

**Comment by willbigas** [comment]
Adicionei uma validação de característica duplicada no mesmo produto e caso por algum motivo ele passe por essa validação eu criei outra logo abaixo que não permite duas opções de características iguais no produto
