### ISSUE TITLE
Criar Contexto Conjunto de Produtos

### ISSUE THREAD

**Issue by willbigas** [strixteam/StrixWeb#59]
Criar uma contexto de Conjunto de produtos em que eu possa agrupar diversos produtos diferentes segundo a minha regra de negócio e criar um valoração unica para esses itens que sobrescreve a valoração unitária do produto

Ex: 
- Cadeira Gamer (500,00)
- Monitor Gamer (800.00)
- Teclado Gamer (250,00)

Total Unitário : 1550,00
Valor do Conjunto : 1300,00

O faturamento de contrato de aluguel, será feito baseado em parametros prédefinidos na empresa
**Valorar a partir do valor do conjunto (Sim , Não)** aberto na issue : #60

O Objetivo é ser um facilitador na hora de selecionar esses produtos Em Operações de Aluguel / Venda

**Comment by LuMistro** [comment]
Permitir que o usuário possa adicionar desconto em campos dinâmicos. Sendo eles, valor bruto(valor em reais) e valor em porcentagem de desconto.
Os campos devem se atualizar dinamicamente.

**Comment by willbigas** [comment]
Testar amplamente esta tela, pois existem alguns cálculos "razoavelmente complicados"
