### ISSUE TITLE
Edição de senha indesejada

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#62]
Quando edito um usuário, sem alterar a senha do mesmo(apenas entrar na edição e salvar o usuário novamente, por exemplo), uma senha aleatória é setada no banco e o usuário salvo não consegue mais logar no sistema até que outro usuário altere a senha do mesmo.

**Comment by willbigas** [comment]
Estranho, eu implementei pra senha só alterar caso o usuário de foco na senha e altere campo antes de salvar, irei verificar novamente

**Comment by willbigas** [comment]
Depurando , descobri que o metodo alterar criado posteriormente estava criptografando a senha armazenada novamente, assim salvando no banco de dados uma nova senha,
Fiz testes e aparentemente foi corrigido, caso volte a acontecer abra uma nova issue.
