### ISSUE TITLE
Melhorar visual Tooltip

### ISSUE THREAD

**Issue by willbigas** [strixteam/StrixWeb#66]
Deixar o visual da tooltip mais amigável pro usuário em todas as telas

![image](https://user-images.githubusercontent.com/40570053/70724600-a3371b00-1cd9-11ea-94b5-820b6781179c.png)

Fazer:
- [x] Alterar Css das tootips

Adicionar html das tooltips nas seguintes telas:
- [x] Cabeçalho
- [x] Edit/Usuário
- [x] Usuário
- [x] Alterar Senha
- [x] Grupo Usuário
- [x] Edit/Empresa Parametro
- [x] Empresa
- [x] Edit/Pessoa
- [x] Fornecedor
- [x] Pessoa
- [x] Pessoa Grupo
- [x] Telefone
- [x] Conjunto
- [x] Edit/Produto
- [x] Característica
- [x] Conversor
- [x] Estoque
- [x] Movimentação
- [x] Produto
- [x] Produto Gerenciar
- [x] Unidade

**Comment by LuMistro** [comment]
Css arrumado no commit 8f4f08701ebcd9e4e92eaa6466037617ef2953c7
