### ISSUE TITLE
Criar edit de Pessoa

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#7]
Criação da tela Edit/Pessoa.xhtml o módulo ERP.

### **Manter Padrões de programação e interface.**

**Comment by willbigas** [comment]
A tela de cadastro de pessoas vai ser uma tela complexa com varias Tabs,
vai ser necessário verifica se a pessoa é Fisica ou juridica para renderizar a Tab adequada de acordo com o tipo de pessoa

#20 Também lembrar de adicionar Integração com a Via Cep no cadastro de endereços

**Comment by willbigas** [comment]
Edit de pessoa já criado nos commits anteriores, abrir novas tasks para novas implementações
