### ISSUE TITLE
Lista de produtos não é adicionada no conjunto de produtos

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#95]
Na página de edição de conjunto de produtos, não consigo adicionar mais de um produto na lista de produtos do conjunto. 
- Estoura um erro no console.
- Quando eu fecho os dialogs e abro a listagem de produtos do conjunto, os produtos aparecem normalmente - Provavelmente foram adicionados na lista da session.
- Quando recarrego a página, os produtos adicionados somem.

**Comment by willbigas** [comment]
Nos meus testes após a correção, tudo está funcionando, caso volte a acontecer abrir nova issue
