### ISSUE TITLE
Não sei o que estou excluindo

### ISSUE THREAD

**Issue by LuMistro** [strixteam/StrixWeb#98]
Na tela de edit de produto, quando vou excluir uma característica do produto, não aparece o nome ou a descrição da característica no modal de confirmação -  o que danifica a interface do sistema e gera incerteza para o usuário de qual objeto ele tenta excluir.

![image](https://user-images.githubusercontent.com/49379484/71301485-696faf80-237e-11ea-96f2-554c9e4281b7.png)

**Comment by willbigas** [comment]
Corrigido !
![image](https://user-images.githubusercontent.com/40570053/71301866-5c08f400-2383-11ea-8c4d-7d60632a8e03.png)
